name: 'git_data_pipeline_demo'
version: '1.0.0'
config-version: 2

profile: 'git_data_pipeline_demo'

model-paths: ['models']
seed-paths: ['seeds']
analysis-paths: ['analyses']
macro-paths: ['macros']

models:
  git_data_pipeline_demo:
    +materialized: view
    
    bronze:
      +schema: bronze
    silver:
      +schema: silver
    gold:
      +schema: gold

seeds:
  git_data_pipeline_demo:
    +schema: raw
