[project]
name = "git-data-pipeline-demo"
version = "0.1.0"
description = "Demo dbt project for showcasing GitHub branching and CI/CD"
requires-python = ">=3.10,<3.14"
dependencies = [
  "dbt-duckdb>=1.8.0,<2.0.0"
]
