models:
  - name: stg_customers
    description: Staged customers from seed data
    columns:
      - name: customer_id
        tests:
          - not_null
          - unique

      - name: email
        tests:
          - not_null

  - name: stg_orders
    description: Staged orders from seed data
    columns:
      - name: order_id
        tests:
          - not_null
          - unique

      - name: customer_id
        tests:
          - not_null

      - name: amount
        tests:
          - not_null

