name: CICD Build

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  dbt-build:
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run dbt (debug + deps + seed + build)
        env:
          MOTHERDUCK_URL: ${{ secrets.MOTHERDUCK_URL }}
          MOTHERDUCK_TOKEN: ${{ secrets.MOTHERDUCK_TOKEN }}
          DBT_SCHEMA_PREFIX: dbt_ci_${{ github.event.pull_request.number }}_${{ GITHUB_SHA::7 }}
        run: |
          uv run dbt deps
          uv run dbt debug --target staging
          uv run dbt build --target staging

      - name: Upload dbt artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: dbt-artifacts
          path: |
            target/**
            logs/**
