name: Production Deployment/Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install the project
        run: uv sync --locked --all-extras

      - name: Run dbt (debug + deps + seed + build)
        env:
          MOTHERDUCK_URL: ${{ secrets.MOTHERDUCK_URL }}
          MOTHERDUCK_TOKEN: ${{ secrets.MOTHERDUCK_TOKEN }}
        run: |
          uv run dbt debug  --target prod
          uv run dbt deps --target prod || true
          uv run dbt seed --target prod --full-refresh
          uv run dbt build --target prod

      - name: Upload dbt artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: dbt-artifacts
          path: |
            target/**
            logs/**

      - name: Generate Docs
        run: |
          uv run dbt docs generate --static
          mkdir docs-tmp
          cp target/static_index.html docs-tmp/index.html
      
      - name: Publish Docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs-tmp
          branch: gh-pages
