name: Get SHA

on:
  workflow_dispatch:

jobs:
  dbt-build:
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Calculate Schema Prefix
        run: echo "${{ github.sha }}:0:6"
